packages:
- '.'
- '.worktrees/deps/status-notifier-item'
- '.worktrees/deps/gtk4-strut'
- '.worktrees/deps/gtk4-sni-tray'
resolver: lts-24.15
extra-deps:
# - gi-gtk-hs-0.3.18   # is not released yet
- github: haskell-gi/haskell-gi
  commit: e2ed85835499f70e119f050a2f37f22481f93886
  subdirs:
  - gi-gtk-hs

nix:
  packages:
    - cairo
    - gcc
    - pango
    - gtk4
    - gtk4-layer-shell
    - hicolor-icon-theme
    - libdbusmenu
    - libdbusmenu-gtk3
    - libxml2
    - pkg-config
    - xorg.libX11
    - xorg.libXScrnSaver
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - zlib
