packages:
- '.'
resolver: lts-24.15
extra-deps:
- gtk-sni-tray-0.1.14.0
- dbus-menu-0.1.3.0
- gtk-strut-0.1.4.0
- status-notifier-item-0.3.2.7
# - gi-gtk-hs-0.3.18   # is not released yet
- github: haskell-gi/haskell-gi
  commit: e2ed85835499f70e119f050a2f37f22481f93886
  subdirs:
  - gi-gtk-hs

nix:
  packages:
    - cairo
    - gcc
    - pango
    - gtk3
    - hicolor-icon-theme
    - libdbusmenu
    - libdbusmenu-gtk3
    - libxml2
    - pkg-config
    - xorg.libX11
    - xorg.libXScrnSaver
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - zlib
