name: Nix
on:
  pull_request:
  push:
    branches: [master]

permissions:
  id-token: "write"
  contents: "read"

jobs:
  lints:
    name: Build and Check with default GHC on ${{ matrix.nixpkgs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Temporarily restrict CI to nixos-unstable while nixos-25.05 is broken.
        nixpkgs: [nixos-unstable]
    env:
      drv: .#packages.x86_64-linux.default
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Use ${{ matrix.nixpkgs }}
        if: matrix.nixpkgs != 'nixos-unstable'
        run: nix flake update nixpkgs --override-input nixpkgs github:NixOS/nixpkgs/${{ matrix.nixpkgs }}
      - name: Run hlint early (short-circuit on lint failures)
        run: nix build --print-build-logs --option substituters "https://cache.nixos.org/" .#checks.x86_64-linux.hlint
      - name: Nix build dependencies
        run: nix develop --print-build-logs "$drv" --command ghc-pkg list
      - name: Nix build
        run: nix build --print-build-logs "$drv"
      - run: nix flake check --print-build-logs
